export const ADD_OUTLET_DETAILS = "ADD_OUTLET_DETAILS";
export const FETCH_OUTLET_DETAILS = "FETCH_OUTLET_DETAILS";
export const FETCH_ALL_FOOD_ITEMS = "FETCH_ALL_FOOD_ITEMS";
export const FETCH_FOOD_ITEMS = "FETCH_FOOD_ITEMS";
export const ADD_FOOD_ITEM = "ADD_FOOD_ITEM";
export const DELETE_FOOD_ITEM = "DELETE_FOOD_ITEM";
